
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./laravel-app:/var/www/html
        depends_on:
            - laravel-app
            - python-parser

    laravel-app:
        build:
            context: ./laravel-app
            dockerfile: Dockerfile
        volumes:
            - ./laravel-app:/var/www/html
        environment:
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
            - PYTHON_PARSER_URL=http://python-parser:5000
        depends_on:
            - db

    python-parser:
        build:
            context: ./python-parser
            dockerfile: Dockerfile
        volumes:
            - ./python-parser:/app
        ports:
            - "5000:5000"

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

    vite:
        image: node:18-alpine
        working_dir: /app
        volumes:
            - ./laravel-app:/app
        ports:
            - "5173:5173"
        command: sh -c "npm install && npm run dev -- --host"

volumes:
    dbdata:
